# Generated by Django 5.2.17 on 2026-09-14 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('issuer', models.CharField(max_length=255)),
                ('year', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('business_case', 'Business Case'), ('business_plan', 'Business Plan'), ('mini_case', 'Mini Case'), ('hackathon', 'Hackathon')], max_length=20)),
                ('level', models.CharField(max_length=100)),
            ],
        ),
    ]
