# Generated by Django 5.2.17 on 2026-09-21 08:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama_institusi', models.CharField(max_length=255)),
                ('jenjang', models.CharField(choices=[('sma_smk', 'SMA/SMK'), ('s1', 'S1'), ('s2', 'S2'), ('s3', 'S3')], default='s1', max_length=20)),
                ('tahun_mulai', models.IntegerField()),
                ('tahun_selesai', models.IntegerField(blank=True, null=True)),
                ('deskripsi', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
