# Generated by Django 5.2.17 on 2026-09-28 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='star_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
